**Project Title :**Predict the heart attack disease for organisationld**WHO(Wor Health Organisation)**, using machine learning algorithm rate of heart attack disease will incresaing and decreasing

**Problem Statment :** The World Health Organisation estimated 17 million death records. Half of the death result is found by us. The reasearch scholar point out the most relavent rsik factor of heart attack as a data science engineer predict the overall risk using machin learning algorithm logistic regression.

Task 1: Import the libraries which required for the the prediction

Task 2: Import the dataset by your work space.

Task 3: Use the appropiate of sklearn libarary to train,test and aplit the dataset.

Task 4: Fit your values with arange function using feature sacling.

Task 5: Check your model accuracy and precision using confusion matrix

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
dataset= pd.read_csv("framingham.csv")
dataset

,male,age,education,currentSmoker,cigsPerDay,BPMeds,prevalentStroke,prevalentHyp,diabetes,totChol,sysBP,diaBP,BMI,heartRate,glucose,TenYearCHD
0,1,39,4.0,0,0.0,0.0,0,0,0,195.0,106.0,70.0,26.97,80.0,77.0,0
1,0,46,2.0,0,0.0,0.0,0,0,0,250.0,121.0,81.0,28.73,95.0,76.0,0
2,1,48,1.0,1,20.0,0.0,0,0,0,245.0,127.5,80.0,25.34,75.0,70.0,0
3,0,61,3.0,1,30.0,0.0,0,1,0,225.0,150.0,95.0,28.58,65.0,103.0,1
4,0,46,3.0,1,23.0,0.0,0,0,0,285.0,130.0,84.0,23.10,85.0,85.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4233,1,50,1.0,1,1.0,0.0,0,1,0,313.0,179.0,92.0,25.97,66.0,86.0,1
4234,1,51,3.0,1,43.0,0.0,0,0,0,207.0,126.5,80.0,19.71,65.0,68.0,0
4235,0,48,2.0,1,20.0,NaN,0,0,0,248.0,131.0,72.0,22.00,84.0,86.0,0
4236,0,44,1.0,1,15.0,0.0,0,0,0,210.0,126.5,87.0,19.16,86.0,NaN,0
4237,0,52,2.0,0,0.0,0.0,0,0,0,269.0,133.5,83.0,21.47,80.0,107.0,0

In [ ]:
dataset.dropna()

,male,age,education,currentSmoker,cigsPerDay,BPMeds,prevalentStroke,prevalentHyp,diabetes,totChol,sysBP,diaBP,BMI,heartRate,glucose,TenYearCHD
0,1,39,4.0,0,0.0,0.0,0,0,0,195.0,106.0,70.0,26.97,80.0,77.0,0
1,0,46,2.0,0,0.0,0.0,0,0,0,250.0,121.0,81.0,28.73,95.0,76.0,0
2,1,48,1.0,1,20.0,0.0,0,0,0,245.0,127.5,80.0,25.34,75.0,70.0,0
3,0,61,3.0,1,30.0,0.0,0,1,0,225.0,150.0,95.0,28.58,65.0,103.0,1
4,0,46,3.0,1,23.0,0.0,0,0,0,285.0,130.0,84.0,23.10,85.0,85.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4231,1,58,3.0,0,0.0,0.0,0,1,0,187.0,141.0,81.0,24.96,80.0,81.0,0
4232,1,68,1.0,0,0.0,0.0,0,1,0,176.0,168.0,97.0,23.14,60.0,79.0,1
4233,1,50,1.0,1,1.0,0.0,0,1,0,313.0,179.0,92.0,25.97,66.0,86.0,1
4234,1,51,3.0,1,43.0,0.0,0,0,0,207.0,126.5,80.0,19.71,65.0,68.0,0
4237,0,52,2.0,0,0.0,0.0,0,0,0,269.0,133.5,83.0,21.47,80.0,107.0,0

In [ ]:
# spliting the  dataset into training set and test set
from sklearn.model_selection import train_test_split

In [ ]:
x=dataset[["age"]]
y=dataset["currentSmoker"]
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.4,random_state=0)

In [ ]:
print(x_train)

[[ 0.   42.    1.   ... 23.43 95.   85.  ]
 [ 0.   60.    2.   ... 24.22 90.   59.  ]
 [ 1.   41.    2.   ... 18.76 65.   60.  ]
 ...
 [ 1.   39.    3.   ... 24.47 70.   81.  ]
 [ 0.   57.    1.   ... 24.27 75.   81.  ]
 [ 0.   40.    2.   ... 26.56 75.   73.  ]]

In [ ]:
print(y_train)

3218    1
590     1
3880    0
1548    0
2601    1
       ..
1033    0
3264    1
1653    1
2607    0
2732    1
Name: currentSmoker, Length: 2542, dtype: int64

In [ ]:
print(x_test)

      age
1669   47
156    58
87     61
685    45
666    57
...   ...
2790   53
1855   66
700    60
2060   38
2348   48

[1696 rows x 1 columns]

In [ ]:
print(y_test)

1669    0
156     0
87      1
685     0
666     0
       ..
2790    0
1855    0
700     0
2060    0
2348    1
Name: currentSmoker, Length: 1696, dtype: int64

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [ ]:
print(x_train)

[[-0.89361628]
 [ 1.21446304]
 [-1.0107318 ]
 ...
 [-1.24496283]
 [ 0.86311649]
 [-1.12784731]]

In [ ]:
print(x_test)

[[-0.30803869]
 [ 0.980232  ]
 [ 1.33157856]
 ...
 [ 1.21446304]
 [-1.36207835]
 [-0.19092317]]

In [ ]:
# feature scalling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [ ]:
print(x_train)

[[-0.89361628]
 [ 1.21446304]
 [-1.0107318 ]
 ...
 [-1.24496283]
 [ 0.86311649]
 [-1.12784731]]

In [ ]:
print(x_test)

[[-0.30803869]
 [ 0.980232  ]
 [ 1.33157856]
 ...
 [ 1.21446304]
 [-1.36207835]
 [-0.19092317]]

In [ ]:
#Training the Logistic Regression model on the Training set

from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0)
classifier.fit(x_train, y_train)

LogisticRegression(random_state=0)

In [ ]:
#Making the Confusion Matrix

from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[503 371]
 [303 519]]

0.6025943396226415

**conclusion**: According to model analysis the LogisticRegression algorithm works succesfully with 0.6 accuracy.
The accuracy shows that building the model is succesfull.